# Generated by Django 6.0 on 2025-12-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WorkShop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پرونده')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن همراه')),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن ثابت یا همراه دیگر')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='سن')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, verbose_name='جنسیت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('medical_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای پزشکی یا عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'ثبت شده'), ('ordered', 'سفارش داده شده'), ('canceled', 'لغو شده'), ('contacted', 'تماس گرفته شد'), ('patient_notified', 'اطلاع\u200cرسانی به بیمار'), ('patient_arrived', 'بیمار مراجعه کرد'), ('delayed', 'تأخیر در مراجعه'), ('delivered', 'تحویل داده شده')], max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت پذیرش / نتیجه تماس')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_history', to='WorkShop.order')),
            ],
            options={
                'verbose_name': 'تاریخچه اقدامات پذیرش',
                'verbose_name_plural': 'تاریخچه اقدامات پذیرش',
                'ordering': ['-changed_at'],
            },
        ),
    ]
