# Generated by Django 6.0 on 2025-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین مراجعه'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('good', 'بیمار خوب'), ('medium', 'بیمار متوسط'), ('bad', 'بیمار بد')], default='medium', max_length=10, verbose_name='نوع بیمار'),
        ),
    ]
