# Generated by Django 6.0 on 2025-12-30 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_patient_attached_to_patient_photo_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'مدرک', 'verbose_name_plural': 'مدارک'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_type',
        ),
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reception.patient', verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پذیرش'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد (شمسی)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='foot_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سایز پا'),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='patient',
            name='orthotic_history',
            field=models.TextField(blank=True, null=True, verbose_name='سوابق استفاده از ارتوتیک'),
        ),
        migrations.AddField(
            model_name='patient',
            name='reception_notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت پذیرش'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referrer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='معرف'),
        ),
        migrations.AddField(
            model_name='patient',
            name='short_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس مختصر'),
        ),
        migrations.AddField(
            model_name='patient',
            name='underlying_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='بیماری\u200cهای زمینه\u200cای'),
        ),
        migrations.AddField(
            model_name='patient',
            name='visit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت مراجعه'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='patients/documents/%Y/%m/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان مدرک'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن همراه دوم'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='attached_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.patient', verbose_name='پیوست به بیمار دیگر'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن همراه اصلی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='عکس بیمار'),
        ),
    ]
