# Generated by Django 6.0 on 2025-12-30 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_alter_document_options_remove_patient_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ معاینه')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='تشخیص')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='توصیه\u200cها و درمان پیشنهادی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای پزشک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پزشک معاینه\u200cکننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='reception.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'معاینه',
                'verbose_name_plural': 'معاینات',
                'ordering': ['-exam_date'],
            },
        ),
    ]
