# Generated by Django 6.0 on 2025-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_examination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='examination',
            name='exercises',
            field=models.TextField(blank=True, null=True, verbose_name='تمرین\u200cها'),
        ),
        migrations.AddField(
            model_name='examination',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='مشاهدات (انتخاب چندتایی یا دستی)'),
        ),
        migrations.AddField(
            model_name='examination',
            name='prescription_designs',
            field=models.TextField(blank=True, null=True, verbose_name='انتخاب طراحی\u200cها (مدیال ودج و ...)'),
        ),
        migrations.AddField(
            model_name='examination',
            name='prescription_services',
            field=models.TextField(blank=True, null=True, verbose_name='تجویز خدمات (کفی، کفش، صندل و ...)'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت معاینه\u200cگر'),
        ),
    ]
