# Generated by Django 6.0 on 2026-01-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_remove_examination_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='prescription_services',
            field=models.JSONField(blank=True, default=dict, verbose_name='تجویز خدمات و طراحی\u200cها'),
        ),
    ]
