# Generated by Django 6.0 on 2025-12-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100, verbose_name='پارامتر')),
                ('right_foot_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='اندازه پای راست')),
                ('left_foot_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='اندازه پای چپ')),
            ],
            options={
                'verbose_name': 'اندازه\u200cگیری',
                'verbose_name_plural': 'اندازه\u200cگیری\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WorkshopStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'ثبت شده'), ('ordered', 'سفارش داده شده'), ('received', 'دریافت شده از تأمین\u200cکننده'), ('in_progress', 'در حال ساخت'), ('ready', 'آماده تحویل'), ('canceled', 'لغو شده'), ('delivered', 'تحویل داده شده')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات کارگاه')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت کارگاه',
                'verbose_name_plural': 'تاریخچه وضعیت\u200cهای کارگاه',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('CNC insole', 'کفی طبی CNC'), ('Functional insole', 'کفی طبی فانکشنال'), ('Pu insole', 'کفی طبی Pu'), ('SandalA', 'صندل آرامو'), ('SandalB', 'صندل بیات'), ('SandalO', 'صندل ارسی')], max_length=20, verbose_name='نوع ارتوز')),
                ('side', models.CharField(choices=[('both', 'هر دو'), ('right', 'راست'), ('left', 'چپ')], max_length=10, verbose_name='اندام مورد نظر')),
                ('different_designs', models.BooleanField(default=False, verbose_name='آیا دو پا متفاوت هستند؟')),
                ('designes_left', models.TextField(blank=True, null=True, verbose_name='طراحی\u200cها - پای چپ')),
                ('designes_right', models.TextField(blank=True, null=True, verbose_name='طراحی\u200cها - پای راست')),
                ('technical_notes_left', models.TextField(blank=True, null=True, verbose_name='خلاصه پرونده - پای چپ')),
                ('technical_notes_right', models.TextField(blank=True, null=True, verbose_name='خلاصه پرونده - پای راست')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('urgent', 'اورژانسی')], default='normal', max_length=10, verbose_name='اولویت')),
                ('send_to', models.CharField(choices=[('workshop', 'کارگاه'), ('examiner', 'اتاق معاینه')], default='workshop', max_length=60, verbose_name='ارسال به')),
                ('status', models.CharField(choices=[('registered', 'ثبت شده'), ('ordered', 'سفارش داده شده'), ('received', 'دریافت شده از تأمین\u200cکننده'), ('in_progress', 'در حال ساخت'), ('ready', 'آماده تحویل'), ('canceled', 'لغو شده'), ('delivered', 'تحویل داده شده')], default='registered', max_length=20, verbose_name='وضعیت')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('workshop_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای کارگاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cدهنده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
