# Generated by Django 6.0 on 2025-12-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('device_type', models.CharField(choices=[('insole', 'کفی طبی'), ('afo', 'AFO'), ('ucbl', 'UCBL'), ('brace', 'بریس')], max_length=20)),
                ('side', models.CharField(choices=[('right', 'راست'), ('left', 'چپ'), ('both', 'هر دو')], max_length=10)),
                ('technical_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('urgent', 'فوری')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('registered', 'ثبت شده'), ('in_progress', 'در حال ساخت'), ('ready', 'آماده')], default='registered', max_length=20)),
                ('workshop_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
