# Generated by Django 6.0 on 2025-12-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0003_order_delivered_at_order_delivered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرونده'),
        ),
    ]
