# Generated by Django 6.0 on 2025-12-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0004_order_case_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='device_type',
            field=models.CharField(choices=[('insole', 'کفی طبی'), ('afo', 'AFO'), ('ucbl', 'UCBL'), ('brace', 'بریس')], max_length=20, verbose_name='نوع ارتوز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient_name',
            field=models.CharField(max_length=100, verbose_name='نام بیمار'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('normal', 'عادی'), ('urgent', 'فوری')], default='normal', max_length=10, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('right', 'راست'), ('left', 'چپ'), ('both', 'هر دو')], max_length=10, verbose_name='اندام مورد نظر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='technical_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای فنی'),
        ),
    ]
