# Generated by Django 6.0 on 2025-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0005_remove_order_phone_alter_order_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='device_type',
            field=models.CharField(choices=[('CNC insole', 'کفی طبی CNC'), ('Functional insole', 'کفی طبی فانکشنال'), ('Pu insole', 'کفی طبی Pu'), ('SandalA', 'صندل آرامو'), ('SandalB', 'صندل بیات'), ('SandalO', 'صندل ارسی')], max_length=20, verbose_name='نوع ارتوز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت شده'), ('ordered', 'سفارش داده شده'), ('received', 'دریافت شده از تأمین\u200cکننده'), ('in_progress', 'در حال ساخت'), ('ready', 'آماده تحویل'), ('canceled', 'لغو شده'), ('delivered', 'تحویل داده شده')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='technical_notes',
            field=models.CharField(blank=True, verbose_name='یادداشت\u200cهای فنی'),
        ),
    ]
