# Generated by Django 6.0 on 2025-12-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0006_alter_order_device_type_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('normal', 'عادی'), ('urgent', 'اورژانسی')], default='normal', max_length=10, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('both', 'هر دو'), ('right', 'راست'), ('left', 'چپ')], max_length=10, verbose_name='اندام مورد نظر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت شده'), ('ordered', 'سفارش داده شده'), ('received', 'دریافت شده از تأمین\u200cکننده'), ('in_progress', 'در حال ساخت'), ('ready', 'آماده تحویل'), ('canceled', 'لغو شده'), ('delivered', 'تحویل داده شده')], default='registered', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='technical_notes',
            field=models.CharField(blank=True, verbose_name='خلاصه پرونده'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='WorkShop.order')),
            ],
        ),
    ]
