# Generated by Django 6.0 on 2025-12-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0008_orderstatushistory_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100, verbose_name='پارامتر')),
                ('right_foot_size', models.CharField(max_length=50, verbose_name='اندازه پای راست')),
                ('left_foot_size', models.CharField(max_length=50, verbose_name='اندازه پای چپ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='WorkShop.order')),
            ],
        ),
    ]
