# Generated by Django 6.0 on 2025-12-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0009_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='designes',
            field=models.CharField(default='', max_length=255, verbose_name='طراحی\u200cها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='technical_notes',
            field=models.CharField(verbose_name='خلاصه پرونده'),
        ),
    ]
