# Generated by Django 6.0 on 2025-12-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0010_order_designes_alter_order_technical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_to',
            field=models.CharField(choices=[('کارگاه', 'کارگاه'), ('اتاق معاینه', 'اتاق معاینه')], default='کارگاه', max_length=60, verbose_name='ارسال به'),
        ),
    ]
