# Generated by Django 6.0 on 2025-12-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0011_order_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='send_to',
            field=models.CharField(choices=[('workshop', 'کارگاه'), ('examiner', 'اتاق معاینه')], default='workshop', max_length=60, verbose_name='ارسال به'),
        ),
    ]
