# Generated by Django 6.0 on 2025-12-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0012_alter_order_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='different_designs',
            field=models.BooleanField(default=False, verbose_name='آیا طراحی\u200cها متفاوت هستند؟'),
        ),
    ]
