# Generated by Django 6.0 on 2025-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0013_order_different_designs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='different_technical_notes',
            field=models.BooleanField(default=False, verbose_name='آیا خلاصه پرونده برای پای چپ و راست متفاوت است؟'),
        ),
        migrations.AlterField(
            model_name='order',
            name='designes',
            field=models.CharField(default='', verbose_name='طراحی\u200cها'),
        ),
    ]
