# Generated by Django 6.0 on 2025-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0014_order_different_technical_notes_alter_order_designes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='designes_left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='designes_right',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='technical_notes_left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='technical_notes_right',
            field=models.TextField(blank=True, null=True),
        ),
    ]
