# Generated by Django 6.0 on 2025-12-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0015_order_designes_left_order_designes_right_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='different_technical_notes',
        ),
        migrations.AlterField(
            model_name='order',
            name='different_designs',
            field=models.BooleanField(default=False, verbose_name='آیا دو پا متفاوت هستند؟'),
        ),
    ]
