# Generated by Django 6.0 on 2025-12-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0016_remove_order_different_technical_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='different_technical_notes',
            field=models.BooleanField(default=False, verbose_name='آیا خلاصه پرونده برای پای چپ و راست متفاوت است؟'),
        ),
    ]
