# Generated by Django 6.0 on 2025-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShop', '0017_order_different_technical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات کارگاه'),
        ),
    ]
